### ISSUE TITLE
ToDo: Legal Info

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#96]
Legal Info 
Beispiel:  http://www.sideshowtoy.com/legal/

**Comment by FrederickChan** [comment]
Make a custom page for this.

**Comment by Catzenjaeger** [comment]
yes this is no problem and is only a todo for myself .. Here i need no help :)

**Comment by Catzenjaeger** [comment]
done - make extra php files in root  well cusiom pages works not 100%

**Comment by FrederickChan** [comment]
Already fix on your site custom page work 100%.. your files were not completely replaced in the server. Lots of them still have an old last-modified date.
